# docker/modules/neo4j.yml
# Docker Compose configuration for the neo4j Knowledge Graph
version: "3.8"

networks:
  llm-stack-network:
    external: true

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION:-5.13.0}
    container_name: neo4j
    volumes:
      - ../data/neo4j/data:/data
      - ../data/neo4j/logs:/logs
      - ../data/neo4j/import:/import
      - ../data/neo4j/plugins:/plugins
    environment:
      # Require explicit configuration of Neo4j credentials
      # Format should be: username/password
      - NEO4J_AUTH=${NEO4J_AUTH:?Neo4j authentication credentials must be explicitly set}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=${NEO4J_ACCEPT_LICENSE_AGREEMENT:-yes}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_INITIAL:-512M}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MAX:-2G}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_PAGECACHE:-512M}
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_connector_https_advertised__address=:7473
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
    ports:
      - "${HOST_PORT_NEO4J_HTTP:-7474}:7474"
      - "${HOST_PORT_NEO4J_BOLT:-7687}:7687"
      - "${HOST_PORT_NEO4J_HTTPS:-7473}:7473"
    deploy:
      resources:
        limits:
          cpus: "${NEO4J_CPU_LIMIT:-0.5}"
          memory: ${NEO4J_MEMORY_LIMIT:-4G}
    restart: unless-stopped
    networks:
      - llm-stack-network
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s